export const informationIds = {
  cfaiPresentation: 'cfaiPresentation',
  examen: 'examen',
  poursuiteEtude: 'poursuiteEtude',
  fisaDefinition: 'fisaDefinition',
  apprenticeshipDefinition: 'apprenticeshipDefinition',
  eligibilityModes: 'eligibilityModes',
  internationalModes: 'internationalModes',
  studentsOpinion: 'studentsOpinion',
  ectsCredits: 'ectsCredits',
  uvVideo: 'uvVideo',
  planningVideo: 'planningVideo',
  diplomaValidation: 'diplomaValidation',
  help: 'help',
};
